### ISSUE TITLE
Final Group Capstone: Kanban Board

### ISSUE THREAD

**Issue by ger619** [ger619/bike-shop-backend#21]
Hello ✋,

- This project has four members: @ger619 @AbuRayhaan @camilevahviraki 

- [ ]  The link to the [Final Capstone Project](https://github.com/users/ger619/projects/2/views/1)

![Screenshot 2022-09-18 at 00 53 05](https://user-images.githubusercontent.com/9010615/190877569-ebcfd27f-8f57-438a-84a6-1d8bbcc88f41.png)

- [ ] Proposed Schema Model

![Screenshot 2022-09-19 at 12 23 15](https://user-images.githubusercontent.com/9010615/190988198-7755ef0f-3807-4892-bcf7-e440a3879731.png)

**Comment by mcrd25** [comment]
Hi Team, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your board.

## Invalid Code Review Request

You have submitted a project, that does not contain a screenshot of the current state of the Kanban Board at the time of review request which is seen as a requirement [here](https://github.com/microverseinc/curriculum-final-capstone/blob/main/projects/setup_kanban_board.md)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear.

**_Please, do not open a new Issue for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by mcrd25** [comment]
Hi Team, 

Great work so far👏 
However there are some issues preventing me from giving the 👍 


- @camilevahviraki has only 12.5 points associated which a 5 or greater difference than the next closest of @AbuRayhaan 32.5pts. @camilevahviraki   needs more tasks assigned so that the share is equitable. i.e. differe < 5 or difference should not be >= 5 among the team . Also @Theophileaseh does not have any issues assigned
- Additionally, all issues should have some weight to it and there were a couple that did not. Please address

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear.

**_Please, do not open a new Issue for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by ger619** [comment]
Hello @mcrd25, Hope all well, thank you for the review, 

I have been unable to find the two people to attend the meeting as we are talking I am waiting for confirmation from student success. We have stalled while we wait for them but unfortunately, we may have to do the project just the two of us i.e. @ger619 and @AbuRayhaan. 
I am not sure how best to proceed as it stands we have to make a decision and proceed even the other tasks assigned to @camilevahviraki may have to be reassigned to the two of us.

Regards

**Comment by mcrd25** [comment]
Let’s see what student success says.

**Comment by vichuge** [comment]
Hi dear student, 

Good job so far!
You still need to work on some issues to prepare your project for the final evaluation, but you are almost there!

![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)


## Suggested changes
_Check the comments under the review._

- There's a task without a description, please add it to the card.
<img width="895" alt="image" src="https://user-images.githubusercontent.com/20563252/191038360-b65240ab-b20a-4ff7-b898-e6f09e7c7c4f.png">

- Please, add the points [Xpts] to these cards. This could help to know the time for work on this.
<img width="539" alt="image" src="https://user-images.githubusercontent.com/20563252/191038606-6e3be020-2a62-405b-bd6f-cc9973f7a7ae.png">

- It looks like there are some issues with some students on this project, but don't worry, remember, you can continue to this project while student success declares a solution for your specific problem. While this happened, try to add the points in a way to all of you (even if the student doesn't attend you, you can change it later) in a way to avoid a diff >= 5 pts on the total for each student. There are some cards without points, so I'm not sure about the total points number for some participants, just try to have this in order to review, if there are some changes in the future for students leaving the project or something else, well, we'll see how this change the board. But at this point, try to complete this. I add the guideline for this point just here:
`
If some student has significantly (difference >= 5 points) more or less points than others - leave a comment in the issue saying that they need to fix it and ask again for a review.
`

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by ger619** [comment]
Hello @vichuge,
Thank you for the feedback.  
The changes have been implemented and I believe we have assigned tasks equally among the 3 of us. 
@camilevahviraki - [25.5pts] @ger619 - [30pts] @AbuRayhaan - [28pts]. We are open to discussion and subject to change. Student success has not responded to my last two requests at Zendesk. At the moment we are proceeding as a team of 3. 

Regards

**Comment by mcrd25** [comment]
Hi Team, 

In my opinion, you are ready to move on to the next step! ⏭️  


Good luck! 🎉 


Feel free to leave any questions or comments in the Issue thread if something is not 100% clear.
